//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace izibiz.COMMON.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("izibiz.COMMON.Language.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kabul Et.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama Ekle.
        /// </summary>
        public static string addDescription {
            get {
                return ResourceManager.GetString("addDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekrar Gönder.
        /// </summary>
        public static string againSent {
            get {
                return ResourceManager.GetString("againSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDATE.
        /// </summary>
        public static string cDate {
            get {
                return ResourceManager.GetString("cDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçimi.
        /// </summary>
        public static string chooseLanguage {
            get {
                return ResourceManager.GetString("chooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database tarafında bır sorun cıktı !.
        /// </summary>
        public static string dbFault {
            get {
                return ResourceManager.GetString("dbFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen faturalar &apos;D:\\temp\\GELEN\\&apos; klasorune kaydedılmıstır.
        /// </summary>
        public static string downInvSaveFolder {
            get {
                return ResourceManager.GetString("downInvSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taslak Faturalar.
        /// </summary>
        public static string draftInvoice {
            get {
                return ResourceManager.GetString("draftInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Arşiv.
        /// </summary>
        public static string eArchive {
            get {
                return ResourceManager.GetString("eArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-İrsailye.
        /// </summary>
        public static string eDispatch {
            get {
                return ResourceManager.GetString("eDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Serbest Meslek.
        /// </summary>
        public static string eFreeJob {
            get {
                return ResourceManager.GetString("eFreeJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Fatura.
        /// </summary>
        public static string eInvoice {
            get {
                return ResourceManager.GetString("eInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Müstahsil.
        /// </summary>
        public static string eManufacturer {
            get {
                return ResourceManager.GetString("eManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZARF ID.
        /// </summary>
        public static string envelopeIdentifier {
            get {
                return ResourceManager.GetString("envelopeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mutabakat.
        /// </summary>
        public static string eReconciliation {
            get {
                return ResourceManager.GetString("eReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalılar.
        /// </summary>
        public static string faulty {
            get {
                return ResourceManager.GetString("faulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | Anasayfa.
        /// </summary>
        public static string formHomePage {
            get {
                return ResourceManager.GetString("formHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | E-Fatura İşlemleri.
        /// </summary>
        public static string formInvoice {
            get {
                return ResourceManager.GetString("formInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | Giriş.
        /// </summary>
        public static string formLoginPage {
            get {
                return ResourceManager.GetString("formLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | E-Fatura Durum Görüntüle.
        /// </summary>
        public static string frmShowInvoiceStatus {
            get {
                return ResourceManager.GetString("frmShowInvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KIMDEN.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Al.
        /// </summary>
        public static string getInvoice {
            get {
                return ResourceManager.GetString("getInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GİB DURUM ACIKLAMA.
        /// </summary>
        public static string gibSatusDescription {
            get {
                return ResourceManager.GetString("gibSatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GİB DURUM KOD.
        /// </summary>
        public static string gibStatusCode {
            get {
                return ResourceManager.GetString("gibStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen Faturalar.
        /// </summary>
        public static string incomingInvoice {
            get {
                return ResourceManager.GetString("incomingInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATURA TURU.
        /// </summary>
        public static string invType {
            get {
                return ResourceManager.GetString("invType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IHRAC TARIH.
        /// </summary>
        public static string issueDate {
            get {
                return ResourceManager.GetString("issueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taslak Faturalar Listesi.
        /// </summary>
        public static string listDraftInvoice {
            get {
                return ResourceManager.GetString("listDraftInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Fatura Listele.
        /// </summary>
        public static string listInvoice {
            get {
                return ResourceManager.GetString("listInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı veya şifre boş bırakılamaz.
        /// </summary>
        public static string loginBadRequest {
            get {
                return ResourceManager.GetString("loginBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giris yapılamadı.. Kullanıcı adı ve kontrol ediniz...
        /// </summary>
        public static string loginWarring {
            get {
                return ResourceManager.GetString("loginWarring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Yeni Fatura.
        /// </summary>
        public static string newInvoice {
            get {
                return ResourceManager.GetString("newInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nolu faturalar uygun degil bu yuzden guncellenmedı.
        /// </summary>
        public static string noInvNotUpdated {
            get {
                return ResourceManager.GetString("noInvNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nolu faturalar guncellendı.
        /// </summary>
        public static string noInvUpdated {
            get {
                return ResourceManager.GetString("noInvUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gösterilecek faturanız yok.
        /// </summary>
        public static string noShowInvoice {
            get {
                return ResourceManager.GetString("noShowInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gösterilecek hatalı faturanız yok.
        /// </summary>
        public static string notFaultyInv {
            get {
                return ResourceManager.GetString("notFaultyInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf İndir.
        /// </summary>
        public static string pdfDownload {
            get {
                return ResourceManager.GetString("pdfDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önizleme.
        /// </summary>
        public static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFİL KIMLIK.
        /// </summary>
        public static string profileid {
            get {
                return ResourceManager.GetString("profileid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenile.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Et.
        /// </summary>
        public static string reject {
            get {
                return ResourceManager.GetString("reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GONDEREN.
        /// </summary>
        public static string sender {
            get {
                return ResourceManager.GetString("sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderilen Faturalar.
        /// </summary>
        public static string sentInvoice {
            get {
                return ResourceManager.GetString("sentInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreyi Göster.
        /// </summary>
        public static string showPassword {
            get {
                return ResourceManager.GetString("showPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURUM.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURUM ACIKLAMA.
        /// </summary>
        public static string statusDesc {
            get {
                return ResourceManager.GetString("statusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı Durum Değiştirme.
        /// </summary>
        public static string succesChangeState {
            get {
                return ResourceManager.GetString("succesChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEDARIKCI.
        /// </summary>
        public static string supplier {
            get {
                return ResourceManager.GetString("supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KIME.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIP.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum Değiştirme Başarısız.
        /// </summary>
        public static string unsuccesChangeState {
            get {
                return ResourceManager.GetString("unsuccesChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum Güncelle.
        /// </summary>
        public static string updateState {
            get {
                return ResourceManager.GetString("updateState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string usurname {
            get {
                return ResourceManager.GetString("usurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETTN.
        /// </summary>
        public static string uuid {
            get {
                return ResourceManager.GetString("uuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturaya yanıt süresi kanuni olarak 8 gündür. Faturanın yanıt süresi geçtiği için yanıt verilemez.
        /// </summary>
        public static string warning8Day {
            get {
                return ResourceManager.GetString("warning8Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMEL FATURAYA YANIT VERILMEZ.
        /// </summary>
        public static string warningBasicInvoice {
            get {
                return ResourceManager.GetString("warningBasicInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturaya yanıt verildiği için ikinci yanıt verilemez.
        /// </summary>
        public static string warningHasAnswer {
            get {
                return ResourceManager.GetString("warningHasAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temel fatura veya 8 gün gecmiş faturaların durum sorgulaması yapılamaz.
        /// </summary>
        public static string warningStateShow {
            get {
                return ResourceManager.GetString("warningStateShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir açıklama yazınız.
        /// </summary>
        public static string writeDescription {
            get {
                return ResourceManager.GetString("writeDescription", resourceCulture);
            }
        }
    }
}
