//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace izibiz.COMMON.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("izibiz.COMMON.Language.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kabul Et.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama Ekle.
        /// </summary>
        public static string addDescription {
            get {
                return ResourceManager.GetString("addDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekleme Başarılı.
        /// </summary>
        public static string addedsucc {
            get {
                return ResourceManager.GetString("addedsucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seri Ön Ek Ekle.
        /// </summary>
        public static string addSeriName {
            get {
                return ResourceManager.GetString("addSeriName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekrar Gönder.
        /// </summary>
        public static string againSent {
            get {
                return ResourceManager.GetString("againSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARSIV FATURA SAYISI.
        /// </summary>
        public static string archiveInvCount {
            get {
                return ResourceManager.GetString("archiveInvCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arşiv Raporları.
        /// </summary>
        public static string archiveReport {
            get {
                return ResourceManager.GetString("archiveReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal Et.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content dıskten sılınmıs ve servısten getırılemedı.
        /// </summary>
        public static string cantGetContent {
            get {
                return ResourceManager.GetString("cantGetContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLUSTURULMA TARİHİ.
        /// </summary>
        public static string cDate {
            get {
                return ResourceManager.GetString("cDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOLUM.
        /// </summary>
        public static string chapter {
            get {
                return ResourceManager.GetString("chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOLUM BITIS.
        /// </summary>
        public static string chapterEnd {
            get {
                return ResourceManager.GetString("chapterEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOLUM BASLANGIC.
        /// </summary>
        public static string chapterStart {
            get {
                return ResourceManager.GetString("chapterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçimi.
        /// </summary>
        public static string chooseLanguage {
            get {
                return ResourceManager.GetString("chooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARA BİRİMİ.
        /// </summary>
        public static string currencyCode {
            get {
                return ResourceManager.GetString("currencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database tarafında bır sorun cıktı !.
        /// </summary>
        public static string dbFault {
            get {
                return ResourceManager.GetString("dbFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACIKLAMA.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen faturalar &apos;D:\\temp\\GELEN\\&apos; klasorune kaydedılmıstır.
        /// </summary>
        public static string downInvSaveFolder {
            get {
                return ResourceManager.GetString("downInvSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taslak Arşivler.
        /// </summary>
        public static string draftArchives {
            get {
                return ResourceManager.GetString("draftArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taslak Faturalar.
        /// </summary>
        public static string draftInvoice {
            get {
                return ResourceManager.GetString("draftInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Arşiv.
        /// </summary>
        public static string eArchive {
            get {
                return ResourceManager.GetString("eArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Arşiv Taslak Faturaları.
        /// </summary>
        public static string eArchiveDraftInvoices {
            get {
                return ResourceManager.GetString("eArchiveDraftInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Arşiv Taslak Faturaları Listele.
        /// </summary>
        public static string eArchiveDraftInvoicesList {
            get {
                return ResourceManager.GetString("eArchiveDraftInvoicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Arşiv Faturaları.
        /// </summary>
        public static string eArchiveInvoices {
            get {
                return ResourceManager.GetString("eArchiveInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Arşiv Fatura Raporları Listele.
        /// </summary>
        public static string eArchiveReportList {
            get {
                return ResourceManager.GetString("eArchiveReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E ARŞİV TİP.
        /// </summary>
        public static string eArchiveType {
            get {
                return ResourceManager.GetString("eArchiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-İrsailye.
        /// </summary>
        public static string eDispatch {
            get {
                return ResourceManager.GetString("eDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Serbest Meslek.
        /// </summary>
        public static string eFreeJob {
            get {
                return ResourceManager.GetString("eFreeJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Fatura.
        /// </summary>
        public static string eInvoice {
            get {
                return ResourceManager.GetString("eInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Müstahsil.
        /// </summary>
        public static string eManufacturer {
            get {
                return ResourceManager.GetString("eManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZARF ID.
        /// </summary>
        public static string envelopeIdentifier {
            get {
                return ResourceManager.GetString("envelopeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mutabakat.
        /// </summary>
        public static string eReconciliation {
            get {
                return ResourceManager.GetString("eReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalılar.
        /// </summary>
        public static string faulty {
            get {
                return ResourceManager.GetString("faulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | E-Arşiv İşlemleri.
        /// </summary>
        public static string formArchive {
            get {
                return ResourceManager.GetString("formArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | Seri Ön Ek Seçimi.
        /// </summary>
        public static string formDialogSeriName {
            get {
                return ResourceManager.GetString("formDialogSeriName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | Anasayfa.
        /// </summary>
        public static string formHomePage {
            get {
                return ResourceManager.GetString("formHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | E-Fatura İşlemleri.
        /// </summary>
        public static string formInvoice {
            get {
                return ResourceManager.GetString("formInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | Giriş.
        /// </summary>
        public static string formLoginPage {
            get {
                return ResourceManager.GetString("formLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | E-Fatura Durum Görüntüle.
        /// </summary>
        public static string frmShowInvoiceStatus {
            get {
                return ResourceManager.GetString("frmShowInvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÖNDEREN MAİL.
        /// </summary>
        public static string fromAlias {
            get {
                return ResourceManager.GetString("fromAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTALDEN MI.
        /// </summary>
        public static string fromPortal {
            get {
                return ResourceManager.GetString("fromPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gib Kullanıcı Listesi Al.
        /// </summary>
        public static string getGibUserList {
            get {
                return ResourceManager.GetString("getGibUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reddedilenler.
        /// </summary>
        public static string getRejected {
            get {
                return ResourceManager.GetString("getRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporlananlar.
        /// </summary>
        public static string getReported {
            get {
                return ResourceManager.GetString("getReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İmzalı Xml Al.
        /// </summary>
        public static string getSignedXml {
            get {
                return ResourceManager.GetString("getSignedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIB ONAYLANMA TARIHI.
        /// </summary>
        public static string gibConfirmationDate {
            get {
                return ResourceManager.GetString("gibConfirmationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GİB DURUM ACIKLAMA.
        /// </summary>
        public static string gibSatusDescription {
            get {
                return ResourceManager.GetString("gibSatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GİB GONDERILME TARIHI.
        /// </summary>
        public static string gibSendDate {
            get {
                return ResourceManager.GetString("gibSendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GİB DURUM KOD.
        /// </summary>
        public static string gibStatusCode {
            get {
                return ResourceManager.GetString("gibStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gib Kullanıcı Listesi.
        /// </summary>
        public static string gibUserList {
            get {
                return ResourceManager.GetString("gibUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secili arsiv raporları basarıyla Kaydedıldı.
        /// </summary>
        public static string hasIdArchiveReportSave {
            get {
                return ResourceManager.GetString("hasIdArchiveReportSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nolu faturalara basarıyla maıl gonderıldı.
        /// </summary>
        public static string hasIdInvoiceSendMail {
            get {
                return ResourceManager.GetString("hasIdInvoiceSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nolu faturalar daha onceden ıptal edılmıs  bunlar ısleme alınmayacak devam etmek istiyor musunuz.
        /// </summary>
        public static string hasNoInvoiceBeforeCanceled {
            get {
                return ResourceManager.GetString("hasNoInvoiceBeforeCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string homePage {
            get {
                return ResourceManager.GetString("homePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen Faturalar.
        /// </summary>
        public static string incomingInvoice {
            get {
                return ResourceManager.GetString("incomingInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATURA TURU.
        /// </summary>
        public static string invType {
            get {
                return ResourceManager.GetString("invType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUZENLENME TARIH.
        /// </summary>
        public static string issueDate {
            get {
                return ResourceManager.GetString("issueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taslak Faturalar Listesi.
        /// </summary>
        public static string listDraftInvoice {
            get {
                return ResourceManager.GetString("listDraftInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrele.
        /// </summary>
        public static string listFilter {
            get {
                return ResourceManager.GetString("listFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Fatura Listele.
        /// </summary>
        public static string listInvoice {
            get {
                return ResourceManager.GetString("listInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portala Yükle.
        /// </summary>
        public static string loadPortal {
            get {
                return ResourceManager.GetString("loadPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı veya şifre boş bırakılamaz.
        /// </summary>
        public static string loginBadRequest {
            get {
                return ResourceManager.GetString("loginBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giris yapılamadı.. Kullanıcı adı ve kontrol ediniz...
        /// </summary>
        public static string loginWarring {
            get {
                return ResourceManager.GetString("loginWarring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIL DURUMU.
        /// </summary>
        public static string mailStatus {
            get {
                return ResourceManager.GetString("mailStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Yeni Fatura.
        /// </summary>
        public static string newInvoice {
            get {
                return ResourceManager.GetString("newInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Getirilemedi.
        /// </summary>
        public static string noGetInvoice {
            get {
                return ResourceManager.GetString("noGetInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nolu faturalar uygun degil bu yuzden guncellenmedı.
        /// </summary>
        public static string noInvNotUpdated {
            get {
                return ResourceManager.GetString("noInvNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nolu faturalar guncellendı.
        /// </summary>
        public static string noInvUpdated {
            get {
                return ResourceManager.GetString("noInvUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gösterilecek faturanız yok.
        /// </summary>
        public static string noShowInvoice {
            get {
                return ResourceManager.GetString("noShowInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gösterilecek hatalı faturanız yok.
        /// </summary>
        public static string notFaultyInv {
            get {
                return ResourceManager.GetString("notFaultyInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        public static string okey {
            get {
                return ResourceManager.GetString("okey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Başarısız.
        /// </summary>
        public static string operationFailed {
            get {
                return ResourceManager.GetString("operationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf İndir.
        /// </summary>
        public static string pdfDownload {
            get {
                return ResourceManager.GetString("pdfDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONEM  BITIS.
        /// </summary>
        public static string periodEnd {
            get {
                return ResourceManager.GetString("periodEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONEM  BASLANGIC.
        /// </summary>
        public static string periodStart {
            get {
                return ResourceManager.GetString("periodStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önizleme.
        /// </summary>
        public static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFİL KIMLIK.
        /// </summary>
        public static string profileid {
            get {
                return ResourceManager.GetString("profileid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALICI VKN/TCKN.
        /// </summary>
        public static string receiverVkn {
            get {
                return ResourceManager.GetString("receiverVkn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenile.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Et.
        /// </summary>
        public static string reject {
            get {
                return ResourceManager.GetString("reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAPOR NO.
        /// </summary>
        public static string reportNo {
            get {
                return ResourceManager.GetString("reportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAPORLANMA  DURUMU.
        /// </summary>
        public static string reportState {
            get {
                return ResourceManager.GetString("reportState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir alıcı posta kutusu seçiniz..
        /// </summary>
        public static string selectAlias {
            get {
                return ResourceManager.GetString("selectAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadece aynı kisiye olan faturaları secebılırsınız.
        /// </summary>
        public static string selectOnePerson {
            get {
                return ResourceManager.GetString("selectOnePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen fatura id için bir seri ön eki seçiniz..
        /// </summary>
        public static string selectSeriName {
            get {
                return ResourceManager.GetString("selectSeriName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GONDEREN AD.
        /// </summary>
        public static string senderName {
            get {
                return ResourceManager.GetString("senderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GONDEREN VKN/TCKN.
        /// </summary>
        public static string senderVkn {
            get {
                return ResourceManager.GetString("senderVkn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GONDERIM TIPI.
        /// </summary>
        public static string sendingType {
            get {
                return ResourceManager.GetString("sendingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nolu faturalara yanıt gonderıldı.
        /// </summary>
        public static string sendResponseToInvoice {
            get {
                return ResourceManager.GetString("sendResponseToInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maile Gönder.
        /// </summary>
        public static string sendToMail {
            get {
                return ResourceManager.GetString("sendToMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderilen Faturalar.
        /// </summary>
        public static string sentInvoice {
            get {
                return ResourceManager.GetString("sentInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seri name; sayı olamaz, bos olamaz,karakter sayısı 3 den kucuk veya kucuk harf olamaz.
        /// </summary>
        public static string seriNameControl {
            get {
                return ResourceManager.GetString("seriNameControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreyi Göster.
        /// </summary>
        public static string showPassword {
            get {
                return ResourceManager.GetString("showPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imzali Xml.
        /// </summary>
        public static string signedXml {
            get {
                return ResourceManager.GetString("signedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURUM.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURUM KODU.
        /// </summary>
        public static string statusCode {
            get {
                return ResourceManager.GetString("statusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURUM ACIKLAMA.
        /// </summary>
        public static string statusDesc {
            get {
                return ResourceManager.GetString("statusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secılı faturalar basarıyla iptal edildi.
        /// </summary>
        public static string succCancelSelectedInvoice {
            get {
                return ResourceManager.GetString("succCancelSelectedInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı Durum Değiştirme.
        /// </summary>
        public static string succesChangeState {
            get {
                return ResourceManager.GetString("succesChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı.
        /// </summary>
        public static string succesful {
            get {
                return ResourceManager.GetString("succesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura yükleme işlemi başarılı..
        /// </summary>
        public static string successLoad {
            get {
                return ResourceManager.GetString("successLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEDARIKCI.
        /// </summary>
        public static string supplier {
            get {
                return ResourceManager.GetString("supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Al.
        /// </summary>
        public static string takeInvoice {
            get {
                return ResourceManager.GetString("takeInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İmzalı Xml Al.
        /// </summary>
        public static string takeSignedXml {
            get {
                return ResourceManager.GetString("takeSignedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALICI MAİL.
        /// </summary>
        public static string toAlias {
            get {
                return ResourceManager.GetString("toAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOPLAM TUTAR.
        /// </summary>
        public static string totalAmount {
            get {
                return ResourceManager.GetString("totalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIP.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum Değiştirme Başarısız.
        /// </summary>
        public static string unsuccesChangeState {
            get {
                return ResourceManager.GetString("unsuccesChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum Güncelle.
        /// </summary>
        public static string updateState {
            get {
                return ResourceManager.GetString("updateState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string usurname {
            get {
                return ResourceManager.GetString("usurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETTN.
        /// </summary>
        public static string uuid {
            get {
                return ResourceManager.GetString("uuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eklemek istediğiniz deger zaten eklenmiş.
        /// </summary>
        public static string valueAlreadyAdded {
            get {
                return ResourceManager.GetString("valueAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanıt Bekleyenler.
        /// </summary>
        public static string waitResponse {
            get {
                return ResourceManager.GetString("waitResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderici posta kutusu bilgilerini cekmek istiyor musunuz? Bu işlem en az 15 dk surer..
        /// </summary>
        public static string wantGetUserList {
            get {
                return ResourceManager.GetString("wantGetUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturaya yanıt süresi kanuni olarak 8 gündür. Faturanın yanıt süresi geçtiği için yanıt verilemez.
        /// </summary>
        public static string warning8Day {
            get {
                return ResourceManager.GetString("warning8Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMEL FATURAYA YANIT VERILMEZ.
        /// </summary>
        public static string warningBasicInvoice {
            get {
                return ResourceManager.GetString("warningBasicInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturaya yanıt verildiği için ikinci yanıt verilemez.
        /// </summary>
        public static string warningHasAnswer {
            get {
                return ResourceManager.GetString("warningHasAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temel fatura veya 8 gün gecmiş faturaların durum sorgulaması yapılamaz.
        /// </summary>
        public static string warningStateShow {
            get {
                return ResourceManager.GetString("warningStateShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Unzip.
        /// </summary>
        public static string withUnzip {
            get {
                return ResourceManager.GetString("withUnzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Zip.
        /// </summary>
        public static string withZip {
            get {
                return ResourceManager.GetString("withZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir açıklama yazınız.
        /// </summary>
        public static string writeDescription {
            get {
                return ResourceManager.GetString("writeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
