//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace izibiz.COMMON.Language {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("izibiz.COMMON.Language.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Kabul Et benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hesap Tipi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string accountType {
            get {
                return ResourceManager.GetString("accountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Açıklama Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string addDescription {
            get {
                return ResourceManager.GetString("addDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ekleme Başarılı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string addedSucc {
            get {
                return ResourceManager.GetString("addedSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satır Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string addRow {
            get {
                return ResourceManager.GetString("addRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seri Ön Ek Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string addSeriName {
            get {
                return ResourceManager.GetString("addSeriName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tekrar Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string againSent {
            get {
                return ResourceManager.GetString("againSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arşiv Fatura Sayısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string archiveInvCount {
            get {
                return ResourceManager.GetString("archiveInvCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arşiv Raporları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string archiveReport {
            get {
                return ResourceManager.GetString("archiveReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arşiv Gönderim Şekli benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string archiveSendingType {
            get {
                return ResourceManager.GetString("archiveSendingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ba Döküman tutarı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string baDocAmount {
            get {
                return ResourceManager.GetString("baDocAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ba Döküman Adeti benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string baDocPiece {
            get {
                return ResourceManager.GetString("baDocPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bs Döküman Tutarı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string bsDocAmount {
            get {
                return ResourceManager.GetString("bsDocAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bs Döküman Adeti benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string bsDocPiece {
            get {
                return ResourceManager.GetString("bsDocPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hesaplanan Tutar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string calculatedTax {
            get {
                return ResourceManager.GetString("calculatedTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İptal Et benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Databaseye ye kayıt basarısız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string cannotSaveDb {
            get {
                return ResourceManager.GetString("cannotSaveDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Content dıskten sılınmıs ve servısten getırılemedı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string cantGetContent {
            get {
                return ResourceManager.GetString("cantGetContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Taşıyıcı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string carrier {
            get {
                return ResourceManager.GetString("carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Taşıyıcı Unvan benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string carrierTitle {
            get {
                return ResourceManager.GetString("carrierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Taşıyıcı Vkn/Tckn benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string carrierVknTckn {
            get {
                return ResourceManager.GetString("carrierVknTckn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oluşturma Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string cDate {
            get {
                return ResourceManager.GetString("cDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bölüm benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string chapter {
            get {
                return ResourceManager.GetString("chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bölüm Bitiş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string chapterEnd {
            get {
                return ResourceManager.GetString("chapterEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bölüm Başlangıç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string chapterStart {
            get {
                return ResourceManager.GetString("chapterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dil Seçimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string chooseLanguage {
            get {
                return ResourceManager.GetString("chooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temizle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem yapmak istediğiniz faturanın bulunduğu satırın uzerıne tıklayınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string clickRowInvoice {
            get {
                return ResourceManager.GetString("clickRowInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cari Mutabakat Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string cmDate {
            get {
                return ResourceManager.GetString("cmDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cari Mutabakatlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string cmReconcilations {
            get {
                return ResourceManager.GetString("cmReconcilations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oluşturma Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string createDate {
            get {
                return ResourceManager.GetString("createDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müstahsil No benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string creditNoteID {
            get {
                return ResourceManager.GetString("creditNoteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Para Birimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string currencyCode {
            get {
                return ResourceManager.GetString("currencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mevcut Tutar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string currentAmount {
            get {
                return ResourceManager.GetString("currentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri Ünvan benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string customerTitle {
            get {
                return ResourceManager.GetString("customerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tarih benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database tarafında bır sorun cıktı ! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string dbFault {
            get {
                return ResourceManager.GetString("dbFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Açıklama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İlçe benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string district {
            get {
                return ResourceManager.GetString("district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boş bırakmayınız lütfen benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string dontEmpty {
            get {
                return ResourceManager.GetString("dontEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gelen faturalar &apos;D:\\temp\\GELEN\\&apos; klasorune kaydedılmıstır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string downInvSaveFolder {
            get {
                return ResourceManager.GetString("downInvSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Taslak Arşivler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string draftArchives {
            get {
                return ResourceManager.GetString("draftArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Taslak Faturalar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string draftInvoice {
            get {
                return ResourceManager.GetString("draftInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E- Arşiv benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string eArchive {
            get {
                return ResourceManager.GetString("eArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E Arşiv Taslak Faturaları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string eArchiveDraftInvoices {
            get {
                return ResourceManager.GetString("eArchiveDraftInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E Arşiv Taslak Faturaları Listele benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string eArchiveDraftInvoicesList {
            get {
                return ResourceManager.GetString("eArchiveDraftInvoicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E Arşiv Faturaları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string eArchiveInvoices {
            get {
                return ResourceManager.GetString("eArchiveInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E Arşiv Fatura Raporları Listele benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string eArchiveReportList {
            get {
                return ResourceManager.GetString("eArchiveReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E Arşiv Tip benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string eArchiveType {
            get {
                return ResourceManager.GetString("eArchiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-İrsailye benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string eDispatch {
            get {
                return ResourceManager.GetString("eDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E- Serbest Meslek benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string eFreeJob {
            get {
                return ResourceManager.GetString("eFreeJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E- Fatura benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string eInvoice {
            get {
                return ResourceManager.GetString("eInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-Müstahsil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string eManufacturer {
            get {
                return ResourceManager.GetString("eManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BA BS Mutabakatlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string emReconcilations {
            get {
                return ResourceManager.GetString("emReconcilations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zarf Id benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string envelopeIdentifier {
            get {
                return ResourceManager.GetString("envelopeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-Mutabakat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string eReconciliation {
            get {
                return ResourceManager.GetString("eReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalılar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string faulty {
            get {
                return ResourceManager.GetString("faulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İzibiz Masaüstü | E-Arşiv İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string formArchive {
            get {
                return ResourceManager.GetString("formArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İzibiz Masaüstü | E-Fatura Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormCreateInvoice {
            get {
                return ResourceManager.GetString("FormCreateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İzibiz Masaüstü | Seri Ön Ek Seçimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string formDialogSeriName {
            get {
                return ResourceManager.GetString("formDialogSeriName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İzibiz Masaüstü | Anasayfa benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string formHomePage {
            get {
                return ResourceManager.GetString("formHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İzibiz Masaüstü | E-Fatura İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string formInvoice {
            get {
                return ResourceManager.GetString("formInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İzibiz Masaüstü | Giriş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string formLoginPage {
            get {
                return ResourceManager.GetString("formLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İzibiz Desktop | Reconcilation benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string formReconcilation {
            get {
                return ResourceManager.GetString("formReconcilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İzibiz Masaüstü | Html Önizleme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string formView {
            get {
                return ResourceManager.GetString("formView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İzibiz Masaüstü | E-Fatura Durum Görüntüle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string frmShowInvoiceStatus {
            get {
                return ResourceManager.GetString("frmShowInvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gönderen Mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fromAlias {
            get {
                return ResourceManager.GetString("fromAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Portaldan benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fromPortal {
            get {
                return ResourceManager.GetString("fromPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gib Kullanıcı Listesi Al benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string getGibUserList {
            get {
                return ResourceManager.GetString("getGibUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reddedilenler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string getRejected {
            get {
                return ResourceManager.GetString("getRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Raporlananlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string getReported {
            get {
                return ResourceManager.GetString("getReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İmzalı Xml Al benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string getSignedXml {
            get {
                return ResourceManager.GetString("getSignedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gib Onaylanma Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gibConfirmationDate {
            get {
                return ResourceManager.GetString("gibConfirmationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gib Durum Açıklama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gibSatusDescription {
            get {
                return ResourceManager.GetString("gibSatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gib Gönderme Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gibSendDate {
            get {
                return ResourceManager.GetString("gibSendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gib Durum Kod benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gibStatusCode {
            get {
                return ResourceManager.GetString("gibStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gib Kullanıcı Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gibUserList {
            get {
                return ResourceManager.GetString("gibUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Secili arsiv raporları basarıyla Kaydedıldı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hasIdArchiveReportSave {
            get {
                return ResourceManager.GetString("hasIdArchiveReportSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nolu faturalara basarıyla maıl gonderıldı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hasIdInvoiceSendMail {
            get {
                return ResourceManager.GetString("hasIdInvoiceSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   nolu mutabak daha once gonderılmıs tekrar gonderemezsınız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hasIdReconBeforeSending {
            get {
                return ResourceManager.GetString("hasIdReconBeforeSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   nolu faturalar daha onceden ıptal edılmıs  bunlar ısleme alınmayacak devam etmek istiyor musunuz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hasNoInvoiceBeforeCanceled {
            get {
                return ResourceManager.GetString("hasNoInvoiceBeforeCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anasayfa benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string homePage {
            get {
                return ResourceManager.GetString("homePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Id benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gelen Faturalar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string incomingInvoice {
            get {
                return ResourceManager.GetString("incomingInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İnternet Satış Bilgisi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string internetSalesInformation {
            get {
                return ResourceManager.GetString("internetSalesInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatura Başlık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string invoiceChapter {
            get {
                return ResourceManager.GetString("invoiceChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatura Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string invoiceInformation {
            get {
                return ResourceManager.GetString("invoiceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatura Türü benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string invType {
            get {
                return ResourceManager.GetString("invType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gönderildi Mi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string isSend {
            get {
                return ResourceManager.GetString("isSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Düzenlenme Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string issueDate {
            get {
                return ResourceManager.GetString("issueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Taslak Faturalar Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string listDraftInvoice {
            get {
                return ResourceManager.GetString("listDraftInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filtrele benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string listFilter {
            get {
                return ResourceManager.GetString("listFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-Fatura Listele benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string listInvoice {
            get {
                return ResourceManager.GetString("listInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Portala Yükle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string loadPortal {
            get {
                return ResourceManager.GetString("loadPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı veya şifre boş bırakılamaz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string loginBadRequest {
            get {
                return ResourceManager.GetString("loginBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giris yapılamadı.. Kullanıcı adı ve kontrol ediniz.. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string loginWarring {
            get {
                return ResourceManager.GetString("loginWarring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E posta benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Durumu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mailStatus {
            get {
                return ResourceManager.GetString("mailStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Durum kodu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mailStatusCode {
            get {
                return ResourceManager.GetString("mailStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aracı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string middleman {
            get {
                return ResourceManager.GetString("middleman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Para Birimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string moneyType {
            get {
                return ResourceManager.GetString("moneyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İsim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +Yeni Fatura benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string newInvoice {
            get {
                return ResourceManager.GetString("newInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Mutabakat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string newReconcilation {
            get {
                return ResourceManager.GetString("newReconcilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hayır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatura Getirilemedi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string noGetInvoice {
            get {
                return ResourceManager.GetString("noGetInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   nolu faturalar uygun degil bu yuzden guncellenmedı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string noInvNotUpdated {
            get {
                return ResourceManager.GetString("noInvNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   nolu faturalar guncellendı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string noInvUpdated {
            get {
                return ResourceManager.GetString("noInvUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gosterilecek mutabakat bulanamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string noReconcilation {
            get {
                return ResourceManager.GetString("noReconcilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gösterilecek faturanız yok benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string noShowInvoice {
            get {
                return ResourceManager.GetString("noShowInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gösterilecek hatalı faturanız yok benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string notFaultyInv {
            get {
                return ResourceManager.GetString("notFaultyInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tamam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string okey {
            get {
                return ResourceManager.GetString("okey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem Başarısız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string operationFailed {
            get {
                return ResourceManager.GetString("operationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ödenecek Tutar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string paidAmount {
            get {
                return ResourceManager.GetString("paidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ödeme Bilgisi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string paymentInformation {
            get {
                return ResourceManager.GetString("paymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pdf İndir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string pdfDownload {
            get {
                return ResourceManager.GetString("pdfDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dönem benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string period {
            get {
                return ResourceManager.GetString("period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dönem Bitiş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string periodEnd {
            get {
                return ResourceManager.GetString("periodEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dönem Başlangıç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string periodStart {
            get {
                return ResourceManager.GetString("periodStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telefon benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Önizleme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string productName {
            get {
                return ResourceManager.GetString("productName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profil Kimlik benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string profileid {
            get {
                return ResourceManager.GetString("profileid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İl benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miktar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gerçek benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string real {
            get {
                return ResourceManager.GetString("real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alıcı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string receiver {
            get {
                return ResourceManager.GetString("receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alıcı VKN/TCKN benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string receiverVkn {
            get {
                return ResourceManager.GetString("receiverVkn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yenile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reddet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string reject {
            get {
                return ResourceManager.GetString("reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satır Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string removeRow {
            get {
                return ResourceManager.GetString("removeRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rapor No benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string reportNo {
            get {
                return ResourceManager.GetString("reportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Raporlanma  Durumu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string reportState {
            get {
                return ResourceManager.GetString("reportState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   islem yapabılmek ıcın tablodan bir veriye  tıklayınız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rowClickForProses {
            get {
                return ResourceManager.GetString("rowClickForProses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satır Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string rowInformation {
            get {
                return ResourceManager.GetString("rowInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Senaryo benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string scenario {
            get {
                return ResourceManager.GetString("scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen bir alıcı posta kutusu seçiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string selectAlias {
            get {
                return ResourceManager.GetString("selectAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sadece aynı kisiye olanları secebılırsınız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string selectOnePerson {
            get {
                return ResourceManager.GetString("selectOnePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen fatura id için bir seri ön eki seçiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string selectSeriName {
            get {
                return ResourceManager.GetString("selectSeriName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gönderen Ad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string senderName {
            get {
                return ResourceManager.GetString("senderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gönderen VKN/TCKN benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string senderVkn {
            get {
                return ResourceManager.GetString("senderVkn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gönderim Tipi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sendingType {
            get {
                return ResourceManager.GetString("sendingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   nolu faturalara yanıt gonderıldı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sendResponseToInvoice {
            get {
                return ResourceManager.GetString("sendResponseToInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maile Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sendToMail {
            get {
                return ResourceManager.GetString("sendToMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gönderilen Faturalar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sentInvoice {
            get {
                return ResourceManager.GetString("sentInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   seri name; bos olamaz,karakter sayısı 3 den kucuk veya kucuk harf olamaz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string seriNameControl {
            get {
                return ResourceManager.GetString("seriNameControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hizmet Toplam Tutar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ServiceTotalAmount {
            get {
                return ResourceManager.GetString("ServiceTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ayarlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifreyi Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string showPassword {
            get {
                return ResourceManager.GetString("showPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   imzali Xml benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string signedXml {
            get {
                return ResourceManager.GetString("signedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Durum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Durum Kodu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string statusCode {
            get {
                return ResourceManager.GetString("statusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Durum Açıklama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string statusDesc {
            get {
                return ResourceManager.GetString("statusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Secılı faturalar basarıyla iptal edildi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string succCancelSelectedInvoice {
            get {
                return ResourceManager.GetString("succCancelSelectedInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı Durum Değiştirme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string succesChangeState {
            get {
                return ResourceManager.GetString("succesChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string succesful {
            get {
                return ResourceManager.GetString("succesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yükleme işlemi başarılı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string successLoad {
            get {
                return ResourceManager.GetString("successLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Servisten durum sorgulama işlemi basarılı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string succGetStatus {
            get {
                return ResourceManager.GetString("succGetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Db ye  durum kaydetme basarılı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string succSaveStatus {
            get {
                return ResourceManager.GetString("succSaveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mail gönderme işlemi basarılı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string succSendMail {
            get {
                return ResourceManager.GetString("succSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tedarikçi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string supplier {
            get {
                return ResourceManager.GetString("supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soyad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatura Al benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string takeInvoice {
            get {
                return ResourceManager.GetString("takeInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İmzalı Xml Al benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string takeSignedXml {
            get {
                return ResourceManager.GetString("takeSignedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kdv Tutarı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string taxAmount {
            get {
                return ResourceManager.GetString("taxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kdv Oranı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string taxPercent {
            get {
                return ResourceManager.GetString("taxPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alıcı Mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string toAlias {
            get {
                return ResourceManager.GetString("toAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplam Tutar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string totalAmount {
            get {
                return ResourceManager.GetString("totalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vergiler Dahil Toplam Tutar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string totalAmountWithTax {
            get {
                return ResourceManager.GetString("totalAmountWithTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tüzel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tuzel {
            get {
                return ResourceManager.GetString("tuzel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tip benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Birim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Birim Miktarı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string unitPrice {
            get {
                return ResourceManager.GetString("unitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Durum Değiştirme Başarısız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string unsuccesChangeState {
            get {
                return ResourceManager.GetString("unsuccesChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Db ye  durum kaydetme basarısız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string unSuccSaveStatus {
            get {
                return ResourceManager.GetString("unSuccSaveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Durum Güncelle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string updateState {
            get {
                return ResourceManager.GetString("updateState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string usurname {
            get {
                return ResourceManager.GetString("usurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ettn benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string uuid {
            get {
                return ResourceManager.GetString("uuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eklemek istediğiniz deger zaten eklenmiş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string valueAlreadyAdded {
            get {
                return ResourceManager.GetString("valueAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vkn/Tckn benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string vknTckn {
            get {
                return ResourceManager.GetString("vknTckn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yanıt Bekleyenler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string waitResponse {
            get {
                return ResourceManager.GetString("waitResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gönderici posta kutusu bilgilerini cekmek istiyor musunuz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string wantGetUserList {
            get {
                return ResourceManager.GetString("wantGetUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uyarı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Faturaya yanıt süresi kanuni olarak 8 gündür. Faturanın yanıt süresi geçtiği için yanıt verilemez benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string warning8Day {
            get {
                return ResourceManager.GetString("warning8Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TEMEL FATURAYA YANIT VERILMEZ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string warningBasicInvoice {
            get {
                return ResourceManager.GetString("warningBasicInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Faturaya yanıt verildiği için ikinci yanıt verilemez benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string warningHasAnswer {
            get {
                return ResourceManager.GetString("warningHasAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   temel fatura veya 8 gün gecmiş faturaların durum sorgulaması yapılamaz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string warningStateShow {
            get {
                return ResourceManager.GetString("warningStateShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hoşgeldiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   With Unzip benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string withUnzip {
            get {
                return ResourceManager.GetString("withUnzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   With Zip benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string withZip {
            get {
                return ResourceManager.GetString("withZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen bir açıklama yazınız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string writeDescription {
            get {
                return ResourceManager.GetString("writeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
